### PR TITLE
Add connection timeout method

### PR DESCRIPTION
**Pull request by mefuwei**
Add tcp dial timeout method

### CODE REVIEW

**Comment by middelink** [comment]
For symetry sake, add a DialTLSTimeout() as well then.

(this is a snippet from how i now work around it)
+       dialer := new(net.Dialer)
+       dialer.Timeout = time.Minute
+       mt.conn, err = tls.DialWithDialer(dialer, "tcp", mt.Address, nil)
+       mt.client, err = ros.NewClient(mt.conn)

**Comment by lampy255** [comment]
This would be a great addition. Can this be merged please?

**Comment by mefuwei** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，你的邮箱已经收到，我会尽快给你回复！

**Comment by archaron** [comment]
Implemented in 3.0.0, thank you!

**Comment by mefuwei** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，你的邮箱已经收到，我会尽快给你回复！

**Pull request closed without merging**
