### PR TITLE
Add post-6.43 login support

### PR DESCRIPTION
**Pull request by archaron**
After the routeros version 6.43, there is a new authorization method.
[https://wiki.mikrotik.com/wiki/Manual:API#Initial_login](https://wiki.mikrotik.com/wiki/Manual:API#Initial_login)

An error message has been changed too.

### CODE REVIEW

**Comment by mdanidl** [comment]
@andre-luiz-dos-santos @go-routeros can you please review and merge, if ok?

**Comment by andre-luiz-dos-santos** [comment]
I´m sorry for the delay.
Would anyone like to maintain this project?

**Comment by mdanidl** [comment]
don't have a huge amount of time either, but you can put me on if you want.

**Comment by archaron** [comment]
@andre-luiz-dos-santos How can I help?

**Comment by andre-luiz-dos-santos** [comment]
@archaron, I have added you as a collaborator here on Github. I think that's enough for you to be able to commit. If you have tested this code and it's working for pre and post 6.43, feel free to merge it.

**Pull request merged**
